### PR TITLE
WIP: Add MSSQL support

### PR DESCRIPTION
**Pull request by jonahgeorge**
Issues:
- [ ] `ActiveRecord::StatementInvalid: TinyTds::Error: ORDER BY items must appear in the select list if SELECT DISTINCT is specified.`
  - https://github.com/jonahgeorge/solid_queue/blob/main/app/models/solid_queue/blocked_execution.rb#L14
- [ ] No `activerecord-sqlserver-adapter` targeting Rails 7.1 (only 7.1.1)
- [ ] Lack of `insert_all` support
  - https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/847
  - https://github.com/jonahgeorge/solid_queue/blob/main/app/models/solid_queue/scheduled_execution.rb#L37
  - https://github.com/jonahgeorge/solid_queue/blob/main/app/models/solid_queue/claimed_execution.rb#L16

### CODE REVIEW

**Comment by justinko** [comment]
I made a suggestion for a gem to add `insert_all` to mssql adapter: https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/869#issuecomment-1870869990

**Comment by justinko** [comment]
Not sure about the `ActiveRecord::StatementInvalid` error but it looks like all the other issues are solvable.

**Comment by erlingur** [comment]
Why was this closed @jonahgeorge? Was excited for this 😀

**Comment by jonahgeorge** [comment]
@erlingur Was just cleaning up my PR backlog on things that are hard blocked. The `insert_all` issue will need to be resolved first and unfortunately I don't have time to look into that. 

Additionally, my confidence in using `MERGE` as the solution to `insert_all` has been decreasing as I read more about it 😓 
- https://www.mssqltips.com/sqlservertip/3074/use-caution-with-sql-servers-merge-statement/
- https://michaeljswart.com/2021/08/what-to-avoid-if-you-want-to-use-merge/

**Comment by erlingur** [comment]
@jonahgeorge Ah ok, fair enough. Hopefully this can be made to work sometime in the future. Thanks for your response! :)

**Pull request closed without merging**
